// AUTO-GENERATED ENUM MIRROR FROM PRISMA

export enum UserStatus {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  PENDING = "PENDING",
  BANNED = "BANNED",
}

export enum ArtworkStatus {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  PUBLIC_REVIEW = "PUBLIC_REVIEW",
  MINTING = "MINTING",
  PUBLISHED = "PUBLISHED",
  PREMIUM = "PREMIUM",
  REJECTED = "REJECTED",
  ARCHIVED = "ARCHIVED",
  HIDDEN = "HIDDEN",
  SOLD = "SOLD",
}

export enum PageStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  HIDDEN = "HIDDEN",
}
