import { prisma } from '@/lib/prisma';

export type DefaultCountry = {
  name: string;
  isoCode: string;
  phoneCode: string;
  sortOrder: number;
};

export const DEFAULT_COUNTRIES: DefaultCountry[] = [
  { name: 'Afghanistan', isoCode: 'AF', phoneCode: '+93', sortOrder: 1 },
  { name: 'Albania', isoCode: 'AL', phoneCode: '+355', sortOrder: 2 },
  { name: 'Algeria', isoCode: 'DZ', phoneCode: '+213', sortOrder: 3 },
  { name: 'American Samoa', isoCode: 'AS', phoneCode: '+1684', sortOrder: 4 },
  { name: 'Angola', isoCode: 'AO', phoneCode: '+244', sortOrder: 5 },
  { name: 'Anguilla', isoCode: 'AI', phoneCode: '+1264', sortOrder: 6 },
  { name: 'Antigua and Barbuda', isoCode: 'AG', phoneCode: '+1268', sortOrder: 7 },
  { name: 'Argentina', isoCode: 'AR', phoneCode: '+54', sortOrder: 8 },
  { name: 'Armenia', isoCode: 'AM', phoneCode: '+374', sortOrder: 9 },
  { name: 'Aruba', isoCode: 'AW', phoneCode: '+297', sortOrder: 10 },
  { name: 'Australia', isoCode: 'AU', phoneCode: '+61', sortOrder: 11 },
  { name: 'Austria', isoCode: 'AT', phoneCode: '+43', sortOrder: 12 },
  { name: 'Azerbaijan', isoCode: 'AZ', phoneCode: '+994', sortOrder: 13 },
  { name: 'Bahrain', isoCode: 'BH', phoneCode: '+973', sortOrder: 14 },
  { name: 'Bangladesh', isoCode: 'BD', phoneCode: '+880', sortOrder: 15 },
  { name: 'Barbados', isoCode: 'BB', phoneCode: '+1246', sortOrder: 16 },
  { name: 'Belarus', isoCode: 'BY', phoneCode: '+375', sortOrder: 17 },
  { name: 'Belgium', isoCode: 'BE', phoneCode: '+32', sortOrder: 18 },
  { name: 'Belize', isoCode: 'BZ', phoneCode: '+501', sortOrder: 19 },
  { name: 'Benin', isoCode: 'BJ', phoneCode: '+229', sortOrder: 20 },
  { name: 'Bermuda', isoCode: 'BM', phoneCode: '+1441', sortOrder: 21 },
  { name: 'Bhutan', isoCode: 'BT', phoneCode: '+975', sortOrder: 22 },
  { name: 'Bolivia', isoCode: 'BO', phoneCode: '+591', sortOrder: 23 },
  { name: 'Bosnia and Herzegovina', isoCode: 'BA', phoneCode: '+387', sortOrder: 24 },
  { name: 'Botswana', isoCode: 'BW', phoneCode: '+267', sortOrder: 25 },
  { name: 'Brazil', isoCode: 'BR', phoneCode: '+55', sortOrder: 26 },
  { name: 'British Indian Ocean Territory', isoCode: 'IO', phoneCode: '+246', sortOrder: 27 },
  { name: 'Brunei', isoCode: 'BN', phoneCode: '+673', sortOrder: 28 },
  { name: 'Bulgaria', isoCode: 'BG', phoneCode: '+359', sortOrder: 29 },
  { name: 'Burkina Faso', isoCode: 'BF', phoneCode: '+226', sortOrder: 30 },
  { name: 'Burundi', isoCode: 'BI', phoneCode: '+257', sortOrder: 31 },
  { name: 'Cambodia', isoCode: 'KH', phoneCode: '+855', sortOrder: 32 },
  { name: 'Cameroon', isoCode: 'CM', phoneCode: '+237', sortOrder: 33 },
  { name: 'Canada', isoCode: 'CA', phoneCode: '+1', sortOrder: 34 },
  { name: 'Cape Verde', isoCode: 'CV', phoneCode: '+238', sortOrder: 35 },
  { name: 'Cayman Islands', isoCode: 'KY', phoneCode: '+1345', sortOrder: 36 },
  { name: 'Central African Republic', isoCode: 'CF', phoneCode: '+236', sortOrder: 37 },
  { name: 'Chad', isoCode: 'TD', phoneCode: '+235', sortOrder: 38 },
  { name: 'Chile', isoCode: 'CL', phoneCode: '+56', sortOrder: 39 },
  { name: 'China', isoCode: 'CN', phoneCode: '+86', sortOrder: 40 },
  { name: 'Christmas Island', isoCode: 'CX', phoneCode: '+61', sortOrder: 41 },
  { name: 'Cocos (Keeling) Islands', isoCode: 'CC', phoneCode: '+61', sortOrder: 42 },
  { name: 'Colombia', isoCode: 'CO', phoneCode: '+57', sortOrder: 43 },
  { name: 'Comoros', isoCode: 'KM', phoneCode: '+269', sortOrder: 44 },
  { name: 'Cook Islands', isoCode: 'CK', phoneCode: '+682', sortOrder: 45 },
  { name: 'Costa Rica', isoCode: 'CR', phoneCode: '+506', sortOrder: 46 },
  { name: 'Croatia', isoCode: 'HR', phoneCode: '+385', sortOrder: 47 },
  { name: 'Cuba', isoCode: 'CU', phoneCode: '+53', sortOrder: 48 },
  { name: 'Cyprus', isoCode: 'CY', phoneCode: '+357', sortOrder: 49 },
  { name: 'Czech Republic', isoCode: 'CZ', phoneCode: '+420', sortOrder: 50 },
  { name: 'Democratic Republic of the Congo', isoCode: 'CD', phoneCode: '+243', sortOrder: 51 },
  { name: 'Denmark', isoCode: 'DK', phoneCode: '+45', sortOrder: 52 },
  { name: 'Djibouti', isoCode: 'DJ', phoneCode: '+253', sortOrder: 53 },
  { name: 'Dominica', isoCode: 'DM', phoneCode: '+1767', sortOrder: 54 },
  { name: 'Dominican Republic', isoCode: 'DO', phoneCode: '+1809', sortOrder: 55 },
  { name: 'East Timor', isoCode: 'TL', phoneCode: '+670', sortOrder: 56 },
  { name: 'Ecuador', isoCode: 'EC', phoneCode: '+593', sortOrder: 57 },
  { name: 'Egypt', isoCode: 'EG', phoneCode: '+20', sortOrder: 58 },
  { name: 'El Salvador', isoCode: 'SV', phoneCode: '+503', sortOrder: 59 },
  { name: 'Equatorial Guinea', isoCode: 'GQ', phoneCode: '+240', sortOrder: 60 },
  { name: 'Eritrea', isoCode: 'ER', phoneCode: '+291', sortOrder: 61 },
  { name: 'Estonia', isoCode: 'EE', phoneCode: '+372', sortOrder: 62 },
  { name: 'Ethiopia', isoCode: 'ET', phoneCode: '+251', sortOrder: 63 },
  { name: 'Falkland Islands', isoCode: 'FK', phoneCode: '+500', sortOrder: 64 },
  { name: 'Faroe Islands', isoCode: 'FO', phoneCode: '+298', sortOrder: 65 },
  { name: 'Federated States of Micronesia', isoCode: 'FM', phoneCode: '+691', sortOrder: 66 },
  { name: 'Fiji', isoCode: 'FJ', phoneCode: '+679', sortOrder: 67 },
  { name: 'Finland', isoCode: 'FI', phoneCode: '+358', sortOrder: 68 },
  { name: 'France', isoCode: 'FR', phoneCode: '+33', sortOrder: 69 },
  { name: 'French Guiana', isoCode: 'GF', phoneCode: '+594', sortOrder: 70 },
  { name: 'French Polynesia', isoCode: 'PF', phoneCode: '+689', sortOrder: 71 },
  { name: 'French Southern and Antarctic Lands', isoCode: 'TF', phoneCode: '', sortOrder: 72 },
  { name: 'Gabon', isoCode: 'GA', phoneCode: '+241', sortOrder: 73 },
  { name: 'Georgia', isoCode: 'GE', phoneCode: '+995', sortOrder: 74 },
  { name: 'Germany', isoCode: 'DE', phoneCode: '+49', sortOrder: 75 },
  { name: 'Ghana', isoCode: 'GH', phoneCode: '+233', sortOrder: 76 },
  { name: 'Gibraltar', isoCode: 'GI', phoneCode: '+350', sortOrder: 77 },
  { name: 'Greece', isoCode: 'GR', phoneCode: '+30', sortOrder: 78 },
  { name: 'Greenland', isoCode: 'GL', phoneCode: '+299', sortOrder: 79 },
  { name: 'Grenada', isoCode: 'GD', phoneCode: '+1473', sortOrder: 80 },
  { name: 'Guadeloupe', isoCode: 'GP', phoneCode: '+590', sortOrder: 81 },
  { name: 'Guam', isoCode: 'GU', phoneCode: '+1671', sortOrder: 82 },
  { name: 'Guatemala', isoCode: 'GT', phoneCode: '+502', sortOrder: 83 },
  { name: 'Guernsey', isoCode: 'GG', phoneCode: '+44', sortOrder: 84 },
  { name: 'Guinea', isoCode: 'GN', phoneCode: '+224', sortOrder: 85 },
  { name: 'Guinea-Bissau', isoCode: 'GW', phoneCode: '+245', sortOrder: 86 },
  { name: 'Guyana', isoCode: 'GY', phoneCode: '+592', sortOrder: 87 },
  { name: 'Haiti', isoCode: 'HT', phoneCode: '+509', sortOrder: 88 },
  { name: 'Heard Island and McDonald Islands', isoCode: 'HM', phoneCode: '', sortOrder: 89 },
  { name: 'Honduras', isoCode: 'HN', phoneCode: '+504', sortOrder: 90 },
  { name: 'Hong Kong', isoCode: 'HK', phoneCode: '+852', sortOrder: 91 },
  { name: 'Hungary', isoCode: 'HU', phoneCode: '+36', sortOrder: 92 },
  { name: 'Iceland', isoCode: 'IS', phoneCode: '+354', sortOrder: 93 },
  { name: 'India', isoCode: 'IN', phoneCode: '+91', sortOrder: 94 },
  { name: 'Indonesia', isoCode: 'ID', phoneCode: '+62', sortOrder: 95 },
  { name: 'Iran', isoCode: 'IR', phoneCode: '+98', sortOrder: 96 },
  { name: 'Iraq', isoCode: 'IQ', phoneCode: '+964', sortOrder: 97 },
  { name: 'Ireland', isoCode: 'IE', phoneCode: '+353', sortOrder: 98 },
  { name: 'Isle of Man', isoCode: 'IM', phoneCode: '+44', sortOrder: 99 },
  { name: 'Israel', isoCode: 'IL', phoneCode: '+972', sortOrder: 100 },
  { name: 'Italy', isoCode: 'IT', phoneCode: '+39', sortOrder: 101 },
  { name: 'Ivory Coast', isoCode: 'CI', phoneCode: '+225', sortOrder: 102 },
  { name: 'Jamaica', isoCode: 'JM', phoneCode: '+1876', sortOrder: 103 },
  { name: 'Japan', isoCode: 'JP', phoneCode: '+81', sortOrder: 104 },
  { name: 'Jersey', isoCode: 'JE', phoneCode: '+44', sortOrder: 105 },
  { name: 'Jordan', isoCode: 'JO', phoneCode: '+962', sortOrder: 106 },
  { name: 'Kazakhstan', isoCode: 'KZ', phoneCode: '+76', sortOrder: 107 },
  { name: 'Kenya', isoCode: 'KE', phoneCode: '+254', sortOrder: 108 },
  { name: 'Kiribati', isoCode: 'KI', phoneCode: '+686', sortOrder: 109 },
  { name: 'Kuwait', isoCode: 'KW', phoneCode: '+965', sortOrder: 110 },
  { name: 'Kyrgyzstan', isoCode: 'KG', phoneCode: '+996', sortOrder: 111 },
  { name: 'Laos', isoCode: 'LA', phoneCode: '+856', sortOrder: 112 },
  { name: 'Latvia', isoCode: 'LV', phoneCode: '+371', sortOrder: 113 },
  { name: 'Lebanon', isoCode: 'LB', phoneCode: '+961', sortOrder: 114 },
  { name: 'Lesotho', isoCode: 'LS', phoneCode: '+266', sortOrder: 115 },
  { name: 'Liberia', isoCode: 'LR', phoneCode: '+231', sortOrder: 116 },
  { name: 'Libya', isoCode: 'LY', phoneCode: '+218', sortOrder: 117 },
  { name: 'Liechtenstein', isoCode: 'LI', phoneCode: '+423', sortOrder: 118 },
  { name: 'Lithuania', isoCode: 'LT', phoneCode: '+370', sortOrder: 119 },
  { name: 'Luxembourg', isoCode: 'LU', phoneCode: '+352', sortOrder: 120 },
  { name: 'Macau', isoCode: 'MO', phoneCode: '+853', sortOrder: 121 },
  { name: 'Madagascar', isoCode: 'MG', phoneCode: '+261', sortOrder: 122 },
  { name: 'Malawi', isoCode: 'MW', phoneCode: '+265', sortOrder: 123 },
  { name: 'Malaysia', isoCode: 'MY', phoneCode: '+60', sortOrder: 124 },
  { name: 'Maldives', isoCode: 'MV', phoneCode: '+960', sortOrder: 125 },
  { name: 'Mali', isoCode: 'ML', phoneCode: '+223', sortOrder: 126 },
  { name: 'Malta', isoCode: 'MT', phoneCode: '+356', sortOrder: 127 },
  { name: 'Marshall Islands', isoCode: 'MH', phoneCode: '+692', sortOrder: 128 },
  { name: 'Martinique', isoCode: 'MQ', phoneCode: '+596', sortOrder: 129 },
  { name: 'Mauritania', isoCode: 'MR', phoneCode: '+222', sortOrder: 130 },
  { name: 'Mauritius', isoCode: 'MU', phoneCode: '+230', sortOrder: 131 },
  { name: 'Mayotte', isoCode: 'YT', phoneCode: '+262', sortOrder: 132 },
  { name: 'Mexico', isoCode: 'MX', phoneCode: '+52', sortOrder: 133 },
  { name: 'Moldova', isoCode: 'MD', phoneCode: '+373', sortOrder: 134 },
  { name: 'Monaco', isoCode: 'MC', phoneCode: '+377', sortOrder: 135 },
  { name: 'Mongolia', isoCode: 'MN', phoneCode: '+976', sortOrder: 136 },
  { name: 'Montserrat', isoCode: 'MS', phoneCode: '+1664', sortOrder: 137 },
  { name: 'Morocco', isoCode: 'MA', phoneCode: '+212', sortOrder: 138 },
  { name: 'Mozambique', isoCode: 'MZ', phoneCode: '+258', sortOrder: 139 },
  { name: 'Namibia', isoCode: 'NA', phoneCode: '+264', sortOrder: 140 },
  { name: 'Nauru', isoCode: 'NR', phoneCode: '+674', sortOrder: 141 },
  { name: 'Nepal', isoCode: 'NP', phoneCode: '+977', sortOrder: 142 },
  { name: 'Netherlands', isoCode: 'NL', phoneCode: '+31', sortOrder: 143 },
  { name: 'New Caledonia', isoCode: 'NC', phoneCode: '+687', sortOrder: 144 },
  { name: 'New Zealand', isoCode: 'NZ', phoneCode: '+64', sortOrder: 145 },
  { name: 'Nicaragua', isoCode: 'NI', phoneCode: '+505', sortOrder: 146 },
  { name: 'Niger', isoCode: 'NE', phoneCode: '+227', sortOrder: 147 },
  { name: 'Nigeria', isoCode: 'NG', phoneCode: '+234', sortOrder: 148 },
  { name: 'Niue', isoCode: 'NU', phoneCode: '+683', sortOrder: 149 },
  { name: 'Norfolk Island', isoCode: 'NF', phoneCode: '+672', sortOrder: 150 },
  { name: 'North Korea', isoCode: 'KP', phoneCode: '+850', sortOrder: 151 },
  { name: 'Northern Mariana Islands', isoCode: 'MP', phoneCode: '+1670', sortOrder: 152 },
  { name: 'Norway', isoCode: 'NO', phoneCode: '+47', sortOrder: 153 },
  { name: 'Oman', isoCode: 'OM', phoneCode: '+968', sortOrder: 154 },
  { name: 'Pakistan', isoCode: 'PK', phoneCode: '+92', sortOrder: 155 },
  { name: 'Palau', isoCode: 'PW', phoneCode: '+680', sortOrder: 156 },
  { name: 'Palestine', isoCode: 'PS', phoneCode: '+970', sortOrder: 157 },
  { name: 'Panama', isoCode: 'PA', phoneCode: '+507', sortOrder: 158 },
  { name: 'Papua New Guinea', isoCode: 'PG', phoneCode: '+675', sortOrder: 159 },
  { name: 'Paraguay', isoCode: 'PY', phoneCode: '+595', sortOrder: 160 },
  { name: 'Peru', isoCode: 'PE', phoneCode: '+51', sortOrder: 161 },
  { name: 'Philippines', isoCode: 'PH', phoneCode: '+63', sortOrder: 162 },
  { name: 'Pitcairn Islands', isoCode: 'PN', phoneCode: '+64', sortOrder: 163 },
  { name: 'Poland', isoCode: 'PL', phoneCode: '+48', sortOrder: 164 },
  { name: 'Portugal', isoCode: 'PT', phoneCode: '+351', sortOrder: 165 },
  { name: 'Puerto Rico', isoCode: 'PR', phoneCode: '+1787', sortOrder: 166 },
  { name: 'Qatar', isoCode: 'QA', phoneCode: '+974', sortOrder: 167 },
  { name: 'Republic of Macedonia', isoCode: 'MK', phoneCode: '+389', sortOrder: 168 },
  { name: 'Republic of the Congo', isoCode: 'CG', phoneCode: '+242', sortOrder: 169 },
  { name: 'Romania', isoCode: 'RO', phoneCode: '+40', sortOrder: 170 },
  { name: 'Russia', isoCode: 'RU', phoneCode: '+7', sortOrder: 171 },
  { name: 'Rwanda', isoCode: 'RW', phoneCode: '+250', sortOrder: 172 },
  { name: 'Réunion', isoCode: 'RE', phoneCode: '+262', sortOrder: 173 },
  { name: 'Saint Helena', isoCode: 'SH', phoneCode: '+290', sortOrder: 174 },
  { name: 'Saint Kitts and Nevis', isoCode: 'KN', phoneCode: '+1869', sortOrder: 175 },
  { name: 'Saint Lucia', isoCode: 'LC', phoneCode: '+1758', sortOrder: 176 },
  { name: 'Saint Pierre and Miquelon', isoCode: 'PM', phoneCode: '+508', sortOrder: 177 },
  { name: 'Saint Vincent and the Grenadines', isoCode: 'VC', phoneCode: '+1784', sortOrder: 178 },
  { name: 'Samoa', isoCode: 'WS', phoneCode: '+685', sortOrder: 179 },
  { name: 'San Marino', isoCode: 'SM', phoneCode: '+378', sortOrder: 180 },
  { name: 'Saudi Arabia', isoCode: 'SA', phoneCode: '+966', sortOrder: 181 },
  { name: 'Senegal', isoCode: 'SN', phoneCode: '+221', sortOrder: 182 },
  { name: 'Serbia', isoCode: 'RS', phoneCode: '+381', sortOrder: 183 },
  { name: 'Seychelles', isoCode: 'SC', phoneCode: '+248', sortOrder: 184 },
  { name: 'Sierra Leone', isoCode: 'SL', phoneCode: '+232', sortOrder: 185 },
  { name: 'Singapore', isoCode: 'SG', phoneCode: '+65', sortOrder: 186 },
  { name: 'Slovakia', isoCode: 'SK', phoneCode: '+421', sortOrder: 187 },
  { name: 'Slovenia', isoCode: 'SI', phoneCode: '+386', sortOrder: 188 },
  { name: 'Solomon Islands', isoCode: 'SB', phoneCode: '+677', sortOrder: 189 },
  { name: 'Somalia', isoCode: 'SO', phoneCode: '+252', sortOrder: 190 },
  { name: 'South Africa', isoCode: 'ZA', phoneCode: '+27', sortOrder: 191 },
  { name: 'South Georgia', isoCode: 'GS', phoneCode: '+500', sortOrder: 192 },
  { name: 'South Korea', isoCode: 'KR', phoneCode: '+82', sortOrder: 193 },
  { name: 'South Sudan', isoCode: 'SS', phoneCode: '+211', sortOrder: 194 },
  { name: 'Spain', isoCode: 'ES', phoneCode: '+34', sortOrder: 195 },
  { name: 'Sri Lanka', isoCode: 'LK', phoneCode: '+94', sortOrder: 196 },
  { name: 'Sudan', isoCode: 'SD', phoneCode: '+249', sortOrder: 197 },
  { name: 'Suriname', isoCode: 'SR', phoneCode: '+597', sortOrder: 198 },
  { name: 'Svalbard and Jan Mayen', isoCode: 'SJ', phoneCode: '+4779', sortOrder: 199 },
  { name: 'Swaziland', isoCode: 'SZ', phoneCode: '+268', sortOrder: 200 },
  { name: 'Sweden', isoCode: 'SE', phoneCode: '+46', sortOrder: 201 },
  { name: 'Switzerland', isoCode: 'CH', phoneCode: '+41', sortOrder: 202 },
  { name: 'Syria', isoCode: 'SY', phoneCode: '+963', sortOrder: 203 },
  { name: 'São Tomé and Príncipe', isoCode: 'ST', phoneCode: '+239', sortOrder: 204 },
  { name: 'Taiwan', isoCode: 'TW', phoneCode: '+886', sortOrder: 205 },
  { name: 'Tajikistan', isoCode: 'TJ', phoneCode: '+992', sortOrder: 206 },
  { name: 'Tanzania', isoCode: 'TZ', phoneCode: '+255', sortOrder: 207 },
  { name: 'Thailand', isoCode: 'TH', phoneCode: '+66', sortOrder: 208 },
  { name: 'The Bahamas', isoCode: 'BS', phoneCode: '+1242', sortOrder: 209 },
  { name: 'The Gambia', isoCode: 'GM', phoneCode: '+220', sortOrder: 210 },
  { name: 'Togo', isoCode: 'TG', phoneCode: '+228', sortOrder: 211 },
  { name: 'Tokelau', isoCode: 'TK', phoneCode: '+690', sortOrder: 212 },
  { name: 'Tonga', isoCode: 'TO', phoneCode: '+676', sortOrder: 213 },
  { name: 'Trinidad and Tobago', isoCode: 'TT', phoneCode: '+1868', sortOrder: 214 },
  { name: 'Tunisia', isoCode: 'TN', phoneCode: '+216', sortOrder: 215 },
  { name: 'Turkey', isoCode: 'TR', phoneCode: '+90', sortOrder: 216 },
  { name: 'Turkmenistan', isoCode: 'TM', phoneCode: '+993', sortOrder: 217 },
  { name: 'Tuvalu', isoCode: 'TV', phoneCode: '+688', sortOrder: 218 },
  { name: 'Uganda', isoCode: 'UG', phoneCode: '+256', sortOrder: 219 },
  { name: 'Ukraine', isoCode: 'UA', phoneCode: '+380', sortOrder: 220 },
  { name: 'United Arab Emirates', isoCode: 'AE', phoneCode: '+971', sortOrder: 221 },
  { name: 'United Kingdom', isoCode: 'GB', phoneCode: '+44', sortOrder: 222 },
  { name: 'United States', isoCode: 'US', phoneCode: '+1', sortOrder: 223 },
  { name: 'Uruguay', isoCode: 'UY', phoneCode: '+598', sortOrder: 224 },
  { name: 'Uzbekistan', isoCode: 'UZ', phoneCode: '+998', sortOrder: 225 },
  { name: 'Vanuatu', isoCode: 'VU', phoneCode: '+678', sortOrder: 226 },
  { name: 'Venezuela', isoCode: 'VE', phoneCode: '+58', sortOrder: 227 },
  { name: 'Vietnam', isoCode: 'VN', phoneCode: '+84', sortOrder: 228 },
  { name: 'Wallis and Futuna', isoCode: 'WF', phoneCode: '+681', sortOrder: 229 },
  { name: 'Western Sahara', isoCode: 'EH', phoneCode: '+212', sortOrder: 230 },
  { name: 'Yemen', isoCode: 'YE', phoneCode: '+967', sortOrder: 231 },
  { name: 'Zambia', isoCode: 'ZM', phoneCode: '+260', sortOrder: 232 },
  { name: 'Zimbabwe', isoCode: 'ZW', phoneCode: '+263', sortOrder: 233 },
];

export async function ensureDefaultCountries() {
  await Promise.all(
    DEFAULT_COUNTRIES.map((country) =>
      prisma.country.upsert({
        where: { isoCode: country.isoCode },
        update: {
          name: country.name,
          phoneCode: country.phoneCode,
          sortOrder: country.sortOrder
        },
        create: {
          ...country,
          allowed: true
        }
      })
    )
  );
}

export async function getAllowedCountries() {
  await ensureDefaultCountries();
  return prisma.country.findMany({
    where: { allowed: true },
    orderBy: [{ name: 'asc' }]
  });
}
